version: '3'
services:
  is-nginx:
    image: nginx:latest
    container_name: is-nginx
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/nginx/identity-nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/ssl/:/etc/nginx/ssl/
# BITSKRAFT IDENTITY CONTAINERS
# IDENTITY STS
  is-sts:
    image: "${STS_IMAGE_REPO}"
    container_name: "${CONTAINER_STS_NAME}"
    restart: unless-stopped
    expose:
      - "9091"  
    ports:
     - "9091:443"
    volumes:
      - ${PWD}/config/sts/appsettings.json:/app/appsettings.json
    env_file:
     - ./is.env
# IDENTITY ADMIN
  is-admin:
    image: "${ADMIN_IMAGE_REPO}"
    container_name: "${CONTAINER_ADMIN_NAME}"
    restart: unless-stopped
    expose:
      - "9092"
    ports:
     - "9092:443"
    volumes:
      - ${PWD}/config/admin/appsettings.json:/app/appsettings.json
    env_file:
     - ./is.env
# IDENTITY API
  is-api:
    image: "${API_IMAGE_REPO}"
    container_name: "${CONTAINER_API_NAME}"
    restart: unless-stopped
    expose:
      - "9093"
    ports:
     - "9093:443"
    volumes:
      - ${PWD}/config/api/appsettings.json:/app/appsettings.json
    env_file:
     - ./is.env
