version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: is-nginx
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/nginx/identity-nginx.conf:/etc/nginx/nginx.conf
      - $PWD/nginx/ssl/:/etc/nginx/ssl/
# BITSKRAFT IDENTITY CONTAINERS
# IDENTITY STS
  identity-sts:
    image: "sneraz/identitysts:latest"
    container_name: is-sts
    restart: unless-stopped
    expose:
      - "9091"  
    ports:
     - "9091:443"
    env_file:
     - ./Identity-sts.env
# IDENTITY ADMIN
  identity-admin:
    image: "sneraz/identityadmin:latest"
    container_name: is-admin
    restart: unless-stopped
    expose:
      - "9092"
    ports:
     - "9092:443"
    env_file:
     - ./Identity-admin.env
# IDENTITY API
  identity-api:
    image: "sneraz/identityapi:latest"
    container_name: is-api
    restart: unless-stopped
    expose:
      - "9093"
    ports:
     - "9093:443"
    env_file:
     - ./Identity-api.env
